#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Site  # The title of the book. Will be placed in the left navbar.
author                      : Mateo Lelong  # The author of the book
copyright                   : "2024"  # Copyright year to be placed in the footer
logo                        : logo.png  # A path to the book logo

execute:
  execute_notebooks: force

latex:
  latex_engine: xelatex
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/TheRayquaza/therayquaza.github.io 
  path_to_book: docs 
  branch: main

html:
  home_page_in_navbar: true
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://therayquaza.github.io
